name: Instagram SMKN 1 Kudus	
on:
  rss:
    url: https://rsshub-ten.vercel.app/picuki/profile/smk_n_1_kudus
jobs:
  email:
    name: Post a email
    runs-on: ubuntu-latest
    steps:
      - name: Send mail
        uses: dawidd6/action-send-mail@v2
        with:
          server_address: web.smkn1kudus.sch.id
          server_port: 465
          username: ${{secrets.MAIL_USERNAME}}
          password: ${{secrets.MAIL_PASSWORD}}
          subject: ${{ on.rss.outputs.title }}
          # Literal body:
          body: ${{ on.rss.outputs.content }}
          # Read file contents as body:
          to: postme@web.smkn1kudus.sch.id
          from: webmaster@web.smkn1kudus.sch.id # <user@example.com>
          # Optional content type (defaults to text/plain):
          content_type: text/html